### ISSUE TITLE
Question about parameters W_q and W_k in adaattention. 

### ISSUE THREAD

**Issue by hanzifan** [genforce/ctrl-x#2]
I think parameters W_q and W_k are fixed, but I'm confused how to get them.

**Comment by kuanhenglin** [comment]
$\mathbf{W}^Q_l$ and $\mathbf{W}^K_l$ are the query and key projection matrices (linear layers) of self-attention layer $l$ before the attention operation. These are from the diffusion model (e.g., SDXL) itself.
