### ISSUE TITLE
how to take the self-recurrence loop?

### ISSUE THREAD

**Issue by findlamp** [genforce/ctrl-x#3]
Do you implement structure and appearance guidance within the self-recurrence loop? Could you provide more detailed information on how this process is carried out?

**Comment by kuanhenglin** [comment]
Self-recurrence is done _without_ structure and appearance control. After each inference step where self-recurrence is enabled (by default we do self-recurrence on timesteps `[0.1, 0.5]`, $n^\textrm{r} = 2$), we apply self-recurrence $n^\textrm{r}$ times. Particularly, after denoising _with_ structure and appearance control, for each self-recurrence step we

1. add enough noise to get back to the previous timestep, and
2. denoise again back to the current timestep _without_ structure and appearance control.

Hope this helps! We also just released our code which will contain more details on how this is done.
